on: [push]
jobs:
  run-windows:
    runs-on: windows-latest
    steps:
      - uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        with:
          ngrok-token: ${{ secrets.NGROK_TOKEN }}
          password: "qwerty12345"

