on: [push]
jobs:
  run-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        with:
          ngrok-token: ${{ secrets.NGROK_TOKEN }}
          password: ${{ secrets.PASSWORD }}
          #foreground: false

